### PR TITLE
Created a simple Hello World Controller/Service

### PR DESCRIPTION
**Pull request by SebbeKarner88**
Pull Request försök // Sebastian Kärner

### CODE REVIEW

**Review by jonsing — CHANGES_REQUESTED** [review]
Are the files in the "libraries" folder suppose to be committed?  Looks like autogenerated files based on the build? I think the whole .idea folder should be excluded. Please correct me if I'm wrong @frykhamn / @SebbeKarner88

**Comment by SebbeKarner88** [comment]
> Are the files in the "libraries" folder suppose to be committed? Looks like autogenerated files based on the build? I think the whole .idea folder should be added to the .gitignore file. Please correct me if I'm wrong @frykhamn / @SebbeKarner88
> 
> Reference: https://github.com/spring-projects/spring-boot/blob/main/.gitignore

I am unsure actually, better run it by Christian i believe, i had to put all those files on ignore to be able to pull the updates. 
hope i didnt break anything :D , havent added anything except my change files.

**Review by Jonathannilsson90 — DISMISSED** [review]
Throughout my little knowledge of Java, this looks great. I approve and take responsibility for any repercussions.

EDIT: Apologizes for any inconvenience this may have caused.

**Comment by frykhamn** [comment]
Where is this? The .idea is added in the .gitignore file in the project I'm
working in?

Den lör 29 apr. 2023 kl 15:31 skrev Sebastian Kärner <
***@***.***>:

**Review by frykhamn — APPROVED** [review]

**Review by frykhamn — APPROVED** [review]

**Review by Jonathannilsson90 — APPROVED** [review]

**Review by frykhamn — APPROVED** [review]

**Pull request closed without merging**
